[workspace]
resolver = "2"
members = [
    "crates/wasi",
    "crates/v86",
    "crates/v86-lib",
    "crates/tuntap",
]

[workspace.dependencies]
v86-wasi = {path = "crates/wasi", version = "0.1.0"}
tuntap = {path = "crates/tuntap", version = "0.1.0"}
json = "0.12"